# Errors
test_that("basb_params throws error if not args are not valid input", {
  expect_error(basb_params(1,1,1,1), "HC/ LC sequence input needs to be a character vector of length 1")
  expect_error(basb_params(TRUE, FALSE, TRUE, FALSE), "HC/ LC sequence input needs to be a character vector of length 1")
  expect_error(basb_params(c("MRGM", "MGRM"), c("MRGM", "MGRM"), "MGRM", c("MRGM", "MGRM")), "HC/ LC sequence input needs to be a character vector of length 1")
  expect_error(basb_params(c("MRGM", "MGRM"), "MGRM", "MGRM", "MGRM"), "HC/ LC sequence input needs to be a character vector of length 1")
  expect_error(basb_params("MGRM", "MGRM", c("MRGM", "MGRM"), "MGRM"), "HC/ LC sequence input needs to be a character vector of length 1")
  expect_error(basb_params("MRGM", "MGRM", "MGYM", "MGXM"), "Input contains:X; Only one letter amino acid codes should be in the input without spaces.")
  expect_error(basb_params("MRGM", "MGRM", "MRX M", "MGXM"), "Input contains:X,  ; Only one letter amino acid codes should be in the input without spaces.")
  expect_error(basb_params("MRGM", "MGRM", "MRGM", "MR}X M"), "Input contains:}, X,  ; Only one letter amino acid codes should be in the input without spaces.")
  expect_error(basb_params("MRGM", "MRGM", "MRGM", "MRGM", 1, 1, 1), "Cyclization, clipping, and glycosylation arguments must be logical.")
  expect_error(basb_params("MRGM", "MRGM", "MRGM", "MRGM", "1", "1", "1"), "Cyclization, clipping, and glycosylation arguments must be logical.")
  # expect_error(basb_params("MRGM", "MRGM", hc_chem_mod = 1), "The chemical modifications needs to be a character vector of length 1.")
  # expect_error(basb_params("MRGM", "MRGM", lc_chem_mod = 1), "The chemical modifications needs to be a character vector of length 1.")
  # expect_error(basb_params("MRGM", "MRGM", hc_chem_mod = 1, lc_chem_mod = 1), "The chemical modifications needs to be a character vector of length 1.")
})
